#!/bin/bash

replace_variables() {
  sed -r "s/&FLAVOUR/LATTE-$2/g;/&ROOT/,\$d" $1
  sed -r "s/^/$4/g;s/&CTP-(\w+)/$3/g" root.css
  sed -r "1,/&ROOT/d" $1
}

mkdir -p src

VARIANTS=(frappe macchiato mocha)

# Generate Styles
for V in ${VARIANTS[@]}
do
  replace_variables style.css ${V^^} "light-dark(var(--ctp-latte-\1), var(--ctp-$V-\1))" > src/catppuccin_latte-$V.css
done

# Generate usersty
replace_variables userstyle.less "" "@\1" "    " > catppuccin.user.less
